import { Open_Sans } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
import { AppProvider } from '@/context/AppContext';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // puedes ajustar los pesos
  variable: '--font-open-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Script src="https://cdn.lordicon.com/lordicon.js" strategy="beforeInteractive" />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
